// Data derived from sir's dataset (Water Use in m3/kg)

const waterData = [
  { name: "bananas", litersPerKg: 5557 },
  { name: "pumpkins", litersPerKg: 8024 },
  { name: "grapes", litersPerKg: 1540 },
  { name: "plums", litersPerKg: 826 },
  { name: "apples", litersPerKg: 2104 },
  { name: "avocados", litersPerKg: 13086 },
  { name: "potatoes", litersPerKg: 18391 },
  { name: "garlic", litersPerKg: 14858 },
  { name: "quinoa", litersPerKg: 14280 },
  { name: "zucchini", litersPerKg: 7109 },
  { name: "beans", litersPerKg: 7461 },
  { name: "tomatoes", litersPerKg: 12573 },
  { name: "cherries", litersPerKg: 13384 },
  { name: "peas", litersPerKg: 14798 },
  { name: "soybeans", litersPerKg: 15810 },
  { name: "barley", litersPerKg: 17130 },
  { name: "blueberries", litersPerKg: 9121 },
  { name: "cotton", litersPerKg: 11583 },
  { name: "squash", litersPerKg: 10048 },
  { name: "peppers", litersPerKg: 598 },
  { name: "pineapples", litersPerKg: 9584 },
  { name: "broccoli", litersPerKg: 19932 },
  { name: "maize", litersPerKg: 9449 },
  { name: "lettuce", litersPerKg: 11629 },
  { name: "onions", litersPerKg: 16423 },
  { name: "peaches", litersPerKg: 10356 },
  { name: "rice", litersPerKg: 1077 },
  { name: "wheat", litersPerKg: 13177 },
  { name: "melons", litersPerKg: 6783 },
  { name: "oats", litersPerKg: 16645 },
  { name: "spinach", litersPerKg: 15696 },
  { name: "corn", litersPerKg: 1655 },
  { name: "strawberries", litersPerKg: 3837 },
  { name: "carrots", litersPerKg: 8529 },
  { name: "cauliflower", litersPerKg: 9180 },
  { name: "mangoes", litersPerKg: 745 },
  { name: "sugarcane", litersPerKg: 8472 }
];
